# Casdoor 应用配置示例（挂载为 /conf/app.conf）
# 详情见 https://casdoor.org/docs/deployment/data-initialization

appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = "user=casdoor password=casdoor host=casdoor-db port=5432 dbname=casdoor sslmode=disable"
tableNamePrefix =
showSql = false
redisEndpoint =
origin = http://localhost:8000
originFrontend =
staticBaseUrl = https://cdn.casbin.org
isDemoMode = false
batchSize = 100
enableErrorMask = false
enableGzip = true
inactiveTimeoutMinutes =
ldapServerPort = 389
radiusServerPort = 1812
radiusSecret = secret
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameCaseSensitive = false
initDataFile = "/conf/init_data.json"
initDataNewOnly = true
